# players

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('content')

Mounted at content

In [3]:
players = pd.read_csv('/content/content/My Drive/Colab Notebooks/coder_school/week_4/assignments/data/06-world-cup/players.csv')
players.sample(10)

        RoundID    MatchID Team Initials  ...          Player Name Position  Event
31783    249722  300061490           PRK  ...         K. MYONG WON       GK    NaN
29867  97410100   97410036           PAR  ...              MONTIEL      NaN    NaN
11212       263       1945           ARG  ...         Mario KEMPES      NaN  OH46'
9277        250       1922           SWE  ...        Leif ERIKSSON      NaN    NaN
8473        536       1635           ENG  ...        Ian CALLAGHAN      NaN    NaN
16190       308        571           URS  ...         Oleg BLOKHIN      NaN   I58'
11709       278       2347           FRA  ...      Christian LOPEZ      NaN    NaN
16705       308        476           URS  ...    Vadim YEVTUSHENKO      NaN    NaN
32440    249722  300061482           ITA  ...         QUAGLIARELLA      NaN    NaN
15552      3475        923           FRG  ...  Karl Heinz FOERSTER      NaN    NaN

[10 rows x 9 columns]